#!/bin/bash

cd /Users/jorgeandresmorenojaimes/Documents/Trabajos/VePorEl/VePorElCliente/
ionic cordova build android --prod --release
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore /Users/jorgeandresmorenojaimes/Documents/Trabajos/colombiaapps.keystore platforms/android/build/outputs/apk/android-release-unsigned.apk jorgemoreno
rm App.apk
~/Library/Android/sdk/build-tools/26.0.0/zipalign -v 4 platforms/android/build/outputs/apk/android-release-unsigned.apk App.apk